/**
 * Enum com as configurações de conexão
 * @author Jorge Augusto C. dos Reis
 * Descrição:
 * Esta classe modela a Janela do Servidor Principal
 */

package servidor;

import base.InfoServidoresEscravos;
import base.InfoDeArquivo;
import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {

        initComponents();

        // Coloca janela no centro da tela
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTabela = new javax.swing.JScrollPane();
        jTableArquivos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelBarraStatus = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemCadServEscravo = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor Principal - Sistema Servidor de Arquivos");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("framePrincipal");
        setResizable(false);

        jTableArquivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Jorge Filho.jpg", "Foto", "Escravo 1", "1 MB"},
                {"02", "Computador", "Foto", "Escravo 2", "1 MB"},
                {"03", "Ainda é cedo.mp3", "Música", "Escravo 1", "3 MB"}
            },
            new String [] {
                "Número", "Nome do Arquivo", "Tipo", "Local", "Tamanho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableArquivos.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTabela.setViewportView(jTableArquivos);
        jTableArquivos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableArquivos.getColumnModel().getColumn(0).setMinWidth(60);
        jTableArquivos.getColumnModel().getColumn(0).setMaxWidth(60);

        jLabel1.setText("Lista de Arquivos Disponíveis");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Escravo 1", "localhost", "2001", "Conectado"},
                {"02", "Escravo 2", "localhost", "2002", "Desconectado"}
            },
            new String [] {
                "Número", "Nome", "IP", "Porta", "Situação"
            }
        ));
        jTable2.setEnabled(false);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setMinWidth(60);
        jTable2.getColumnModel().getColumn(0).setMaxWidth(60);
        jTable2.getColumnModel().getColumn(2).setMinWidth(100);
        jTable2.getColumnModel().getColumn(2).setMaxWidth(100);
        jTable2.getColumnModel().getColumn(3).setMinWidth(60);
        jTable2.getColumnModel().getColumn(3).setMaxWidth(60);
        jTable2.getColumnModel().getColumn(4).setMinWidth(100);
        jTable2.getColumnModel().getColumn(4).setMaxWidth(100);

        jLabel2.setText("Lista de Escravos");

        jLabelBarraStatus.setText("Carregando...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBarraStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBarraStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuArquivo.setText("Arquivo");

        jMenuItemCadServEscravo.setText("Cadastrar Servidor Escravo");
        jMenuItemCadServEscravo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadServEscravoActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemCadServEscravo);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSair);

        jMenuBar.add(jMenuArquivo);

        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar.add(jMenuAjuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        exibirSobre();
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        sairDoPrograma();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadServEscravoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadServEscravoActionPerformed
        cadastrarServidoresEscravos();
    }//GEN-LAST:event_jMenuItemCadServEscravoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Janela janela = new Janela();

                janela.setVisible(true);

                /**
                 * Cria a nova GerenteConexao que irá responder as solicitações
                 * a partir dela cria uma nova thread
                 * isso poderia ficar em uma só linha como em:
                 * new Thread(new GerenteConexao(janela.jLabelBarraStatus)).start();
                 * Mas para que possamos referencia tando a instância de GerenteConexao
                 * como de Thread, resolvi colocar desta forma
                 */
                janela.gerenteConexao   = new GerenteConexao(janela.jLabelBarraStatus);
                janela.threadDoServidor = new Thread(janela.gerenteConexao);
                janela.threadDoServidor.start();

                // Atualiza a lista dos arquivos...
                janela.carregarListaServidoresEscravos();
                janela.atualizaListagemDeArquivos();
                janela.atualizarTabelaArquivos();
            }
        });
    }

    /* Aqui inicia a implementaçãos dos meus métodos, deste ponto em diante
     * não existe código que não tenha sido feito por mim.
     */

    // Método que exibe a mensagem do Sobre
    private void exibirSobre() {
        JOptionPane.showMessageDialog(rootPane,
        "<html><b><font size='5'>Sistema Servidor de Arquivos</font></b><br>"                   +
        "<b><font size='3'>IESAM - Institudo de Estudos Superiores da Amazônia</font></b><br>"  +
        "<b><font size='3'>Engenharia de Computação</font></b><br><br>"                         +
        "Programador: <b><font color='red'>Jorge Augusto C. dos Reis</font></b><br>"            +
        "E-mail: <b><font color='blue'>engjorgeaugusto@gmail.com</font></b><br>",
        "Sobre", JOptionPane.INFORMATION_MESSAGE);

        // "E-mail: <a href='mailto:engjorgeaugusto@hotmail.com'>engjorgeaugusto@hotmail.com</a></html>",
    }

    // Este método fecha o programa
    private void sairDoPrograma() {
        dispose();
    }

    // Este método abria a janela de cadastro de servidores escravos
    private void cadastrarServidoresEscravos() {
        cadServidoresEscravos = new CadServidoresEscravos(this, true);

        // coloca cadastro de servidores escravos no centro desta tela...
        cadServidoresEscravos.setLocationRelativeTo(this);
        cadServidoresEscravos.setVisible(true);
    }

    // Este método carrega a lista de servidores escravos do arquivos em disco
    private void carregarListaServidoresEscravos() {
        try {
            FileInputStream        arquivo     = new FileInputStream("ListaDeServidoresEscravos.txt");
            ObjectInputStream      leitor      = new ObjectInputStream(arquivo);

            listaServEscravos = (ArrayList<InfoServidoresEscravos>) leitor.readObject();
        }
        catch(Exception ex) {
            JOptionPane.showConfirmDialog(null, ex.getMessage(),
                                         "Erro ao ler lista",
                                         JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Atualiza a listagem dos arquivos, este método é synchronized para evitar
     * erros de sincronização
     */
    private synchronized void  atualizaListagemDeArquivos() {
        for(InfoServidoresEscravos servEscravo : listaServEscravos) {
            solicitarListagemDeArquivos(servEscravo);
        }
    }

    /**
    * Solicitar listagem dos arquivos
    * Este método vai solicitar aos vários servidores escravos que informem
    * a listagem dos vários arquivos que eles tem disponíveis, ele será chamaod de dentro do
    * do método solicitarArquivos() ai é cima, para cada uma dos vários servidores
    * constantes na lista de servidores escravos, no momento ele e lista os arquivos
    * existentes na pasta: ArquivosDistribuídos, mais isso vai mudar, para que
    * lista os arquivos existentes no servidores escravos
    */
    private void solicitarListagemDeArquivos(InfoServidoresEscravos servEscravo) {
        jLabelBarraStatus.setText("Atualizando listagem de arquivos, aguarde...");
        try {
            File    pasta       = new File("ArquivosDistribuidos");
            // para cada arquivo existente na pasta, cria um item no ArrayList


            // Isto deve sair daqui depois quando estiver comunicando com os vários
            // servidores escravos...
            listaDeArquivos.clear();

            for(File arquivo : pasta.listFiles()) {
                if(arquivo.isFile()) {
                    InfoDeArquivo infoArquivo = new InfoDeArquivo(arquivo.getName(), "Local", 1000);
                    listaDeArquivos.add(infoArquivo);
                }
            }

            jLabelBarraStatus.setText("Total de Arquivos Lidos: " + listaDeArquivos.size());
        }
        catch(Exception ex) {
            jLabelBarraStatus.setText("Erro ao solicitar listagem de arquivos: " + ex.getMessage());
        }
    }

    // Este método transforma preenche a JTable com os dados dos arquivos...
    private void atualizarTabelaArquivos() {
        DefaultTableModel modelo = (DefaultTableModel) jTableArquivos.getModel();
        modelo.setRowCount(0);

        // Adiciona linhas a tabela...
        jLabelBarraStatus.setText("Total de Arquivos: " + listaDeArquivos.size());

        for(InfoDeArquivo arquivo : listaDeArquivos) {
            String[] array = {"0",
                              arquivo.getNome(),
                              "Tipo",
                              arquivo.getLocal(),
                              Integer.toString(arquivo.getTamanho())};

            modelo.addRow(array);
        }
    }

    /* Declaração das minhas varíaveis
     *
     */
    private Thread                              threadDoServidor;
    private GerenteConexao                      gerenteConexao;
    private CadServidoresEscravos               cadServidoresEscravos;      // referência a janela de cadastro
    private ArrayList<InfoServidoresEscravos>   listaServEscravos   = new ArrayList<InfoServidoresEscravos>();
    private ArrayList<InfoDeArquivo>            listaDeArquivos     = new ArrayList<InfoDeArquivo>();

    // Fim das Minhas Declarações

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBarraStatus;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCadServEscravo;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneTabela;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableArquivos;
    // End of variables declaration//GEN-END:variables
}
