/**
 * Classe que modela a GUI da Janela de Configuração de Conexão com o Servidor
 * @author: Jorge Augusto C. dos Reis
 * @data..: 18/03/2013 às 04:34
 * @Descrição:
 * Esta classe modela a GUI da Janela de configuração da conexão com o servidor
 * basicamente ela carrega e salva as informações ta JTable em um arquivo,
 * usando os métodos da classe InfoServidor
 */

package escravo;

import base.InfoServidor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JanelaConfigConServidor extends javax.swing.JDialog {

    /**
     * Creates new form JanelaCadServEscravo
     */
    public JanelaConfigConServidor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Coloca janela no centro da tela
        setLocationRelativeTo(null);
        janelaPai = (JanelaEscravo) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEditar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConfigCon = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuração de Conexão com Servidor Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                windowOpenedActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jTableConfigCon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome*", "IP", "Porta"
            }
        ));
        jTableConfigCon.setColumnSelectionAllowed(true);
        jTableConfigCon.setEnabled(false);
        jTableConfigCon.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableConfigCon);
        jTableConfigCon.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableConfigCon.getColumnModel().getColumn(0).setMinWidth(150);
        jTableConfigCon.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTableConfigCon.getColumnModel().getColumn(0).setMaxWidth(60150);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFechar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        fecharJanela();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        salvaConfiConServidor();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void windowOpenedActionPerformed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowOpenedActionPerformed
        carregaConfigConServidor();
    }//GEN-LAST:event_windowOpenedActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        habilitaEdicao();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    /* Aqui inicia a implementaçãos dos meus métodos, deste ponto em diante
     * não existe código que não tenha sido feito por mim.
     */

    // Este método fecha a janela de cadatro de servidores escravos
    private void fecharJanela() {
        dispose();
    }

    /**
     * Carrega informações de conexão com o servidor principal, apartir do arquivo
     * caso o arquivo de configuração não exista, cria o mesmo e carrefa
     */
    private void carregaConfigConServidor() {
        InfoServidor infoServidor = janelaPai.getEscravo().getInfoServidor();
        DefaultTableModel   model = (DefaultTableModel) jTableConfigCon.getModel();

        model.setRowCount(0);
        model.addRow(new String[]{infoServidor.getNome(),
                                  infoServidor.getIp(),
                                  Integer.toString(infoServidor.getPorta())});
    }


    /**
     * Este método salva as alterações feitas no arquivo de configuração de
     * conexão com o servidor
     */
    private void salvaConfiConServidor() {
        DefaultTableModel   model = (DefaultTableModel) jTableConfigCon.getModel();
        List linha = (List) model.getDataVector().get(0);

        try {
            // Cria objeto de InfoServidor com os dados da JTable
            InfoServidor infoServidor = new InfoServidor(
                                            linha.get(0).toString(),
                                            linha.get(1).toString(),
                                            Integer.parseInt(linha.get(2).toString()));

            janelaPai.getEscravo().setInfoServidor(infoServidor);
            InfoServidor.salvaEmArquivo(janelaPai.getEscravo().getInfoServidor(), Escravo.ARQ_CONFIG_CON_SERVIDOR);
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(rootPane,
                    "Erro ao salvar informações de configuração",
                    "Erro ao Salvar", JOptionPane.ERROR_MESSAGE);
        }

        // Troca o estado do botão de edição e recarrega pra ter certeza que foi salvo
        habilitaEdicao();
    }

    /**
     * Este método habilida edição da tabela
     */
    private void habilitaEdicao() {
        if(!jTableConfigCon.isEnabled()) {
            jTableConfigCon.setEnabled(true);
            jButtonEditar.setText("Cancelar");
            jButtonSalvar.setEnabled(true);
        }
        else {
            jTableConfigCon.editingCanceled(null);
            jTableConfigCon.clearSelection();
            jTableConfigCon.setEnabled(false);
            jButtonEditar.setText("Editar");
            jButtonSalvar.setEnabled(false);

            // Recarrega arquivo, cancelando qualquer alteração
            carregaConfigConServidor();
        }
    }

    /**
     * Declaração dos meus atributos.
     */
    JanelaEscravo janelaPai;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConfigCon;
    // End of variables declaration//GEN-END:variables

}
